### PR TITLE
closes #2

### LINKED ISSUE #2: [FIX] Excessive Padding in Hero Section
## Problem Description

The padding bottom and top for the main hero section is too much, causing the main section to be too big and making the page scroll.

## Solution

Refer to the [document component](https://github.com/HpatricioH/SlugLink/blob/main/src/app/page.tsx) to implement the necessary changes. Specifically, focus on line 10 to adjust the padding, remove excess bottom padding, and reduce the top margin of the section.

## Visual Reference

Attached is an image highlighting the problem. This will provide a visual understanding of the issue that needs to be addressed.

SlugLink Issue

Feel free to reach out if you have any questions or need further assistance.

### PR DESCRIPTION
**Pull request by AKHIL-DyC**
closing the scroll issue

### CODE REVIEW

**Review by HpatricioH — CHANGES_REQUESTED** [review]
With these changes, there isn't much separation between elements. 

We can leave a gap between elements by perhaps only changing the `py-12` padding in [page](https://github.com/HpatricioH/SlugLink/blob/main/src/app/page.tsx) line 10. 

We can remove the padding at the bottom and reduce the top padding to something smaller, but still have space between the nav bar and SLUGLINK, I liked your idea of reducing the padding between the SLUGLINK and the cards  we can keep that. 

This changes will look better for xl media query.

**Comment by AKHIL-DyC** [comment]
@HpatricioH done

**Review by HpatricioH — APPROVED** [review]

**Review by HpatricioH — CHANGES_REQUESTED** [review]
When previewing the deployment, these changes are affecting the background image.

image

This is regarding the media query for extra-large (xl) and beyond. I suggest only changing py-12 to pt-4 pb-2 in the page.tsx file and no other changes. I am curious if any other changes applied to this have broken the background. I won't merge it for now.

**Comment by HpatricioH** [comment]
Closing pull request for inactivity

**Pull request closed without merging**
